version: "2"
volumes:
  node_modules:

services:
  relay:
    # container_name: relay
    # build:
    #   context: .
    #   dockerfile: Dockerfile.relay
    # # volumes:
    # #   - node_modules:/relay/node_modules.relay
    volumes:
      # - .:/relay
      - .lnd/:/relay/.lnd

    container_name: relay
    image: cryptoforge/n2n2-relay

    mem_limit: 512M
    mem_reservation: 256M

    ports:
      - "8080:8080"
      - "3000:3000"
      - "9735:9735"
      - "10009:10009"
      - "8333:8333"

    command: "lnd --accept-keysend --configfile=/relay/.lnd/lnd.conf && npm start"

    environment:
      - NODE_ENV=production
      - PORT=3000
      - NODE_DOMAIN=$NODE_DOMAIN
      - NODE_IP=$NODE_IP
      - NODE_ALIAS=$NODE_ALIAS
      - TRIBES_HOST=$TRIBES_HOST
      - MEDIA_HOST=$MEDIA_HOST
      - MACAROON_LOCATION=$MACAROON_LOCATION

    env_file:
      - /etc/environment

  thunderhub:
    container_name: thunderhub
    image: apotdevin/thunderhub:v0.12.19
    ports:
      - "3001:3000"

    volumes:
      # - .:/relay
      - .lnd/:/relay/.lnd

  game:
    container_name: game
    build:
      context: .
      dockerfile: Dockerfile.game
    # volumes:
    #   - node_modules:/relay/node_modules

    mem_limit: 2048M
    mem_reservation: 2048M
    ports:
      - "8443:8443"
    command: "npm start"
    env_file:
      - /etc/environment
