version: "2"
volumes:
  node_modules:

services:
  reverse-proxy:
    container_name: proxy
    # The official v2 Traefik docker image
    image: traefik:v2.2.1
    # Enables the web UI and tells Traefik to listen to docker
    # command: --configFile=/home/ec2-user/sphinx-deploy/traefik.yaml
    command:
      # - "--log.level=DEBUG"
      - "--logLevel=DEBUG"
      - "--traefikLog.filePath=/var/log/traefik.log"
      - "--traefikLog.format=json"
      - "--accessLog.filePath=/var/log/access.log"
      - "--accessLog.format=json"
    ports:
      # The HTTP port
      # - 80:80
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080
      # entrypoints
      - 443:443
      - 5000:5000
      # - 3001:3001
      # - 3000:3000
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik.yaml:/etc/traefik/traefik.yaml
      - ./docker/letsencrypt:/letsencrypt

    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION

    logging:
      options:
        max-size: 10m

    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000

  thunderhub:
    container_name: thunderhub
    image: apotdevin/thunderhub:v0.12.19

    ports:
      - "3000:3000"

    # expose:
    #   - "3000"

    volumes:
      - .lnd/:/relay/.lnd

    # command: "npm run start:secure"

    environment:
      - COOKIE_PATH=/relay/.lnd/.cookie
      - SSO_SERVER_URL=127.0.0.1:10009
      - SSO_CERT_PATH=/relay/.lnd/tls.cert
      - SSO_MACAROON_PATH=/relay/.lnd/data/chain/bitcoin/mainnet
      - ACCOUNT_CONFIG_PATH=/relay/.lnd/thubConfig.yaml
      # - ZEROSSL_API_KEY=ce32f78e759853c4408226c15ab76aa4
      - PUBLIC_URL=game-1.playentertainment.online
      - SSL_PORT=80

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.thunderhub.tls=true"

      - "traefik.http.routers.thunderhub.rule=Host(`game-1.playentertainment.online`)"
      - "traefik.http.services.thunderhub.loadbalancer.server.port=3000"
      - "traefik.http.routers.thunderhub.tls.certresolver=myresolver"
      - "traefik.http.routers.thunderhub.entrypoints=websecure"
      # - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

      # - "traefik.backend=dashboard"
      # - "traefik.docker.network=web"
      # - "traefik.frontend.rule=Host:game-1.playentertainment.online"
      # - "traefik.enable=true"
      # - "traefik.port=3000"

    depends_on:
      - reverse-proxy
# networks:
#   web:
#     external: true
