---
- name: Print ansible_hostname
  debug: var=ansible_hostname

- name: Print inventory_hostname
  debug: var=inventory_hostname

- name: Print testnet information
  debug: var=hostvars[inventory_hostname].testnet

- name: Print ansible_hostname
  debug: var=ansible_host

- name: Set environment variables.
  copy:
    dest: /etc/environment
    content: |
      {{ lookup('file', 'vars/.env') }}
  become: yes

- name: Set NODE_DOMAIN
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^NODE_DOMAIN"
    line: "NODE_DOMAIN={{ inventory_hostname }}"
  become: yes

- name: Set NODE_IP
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^NODE_IP"
    line: "NODE_IP={{ ansible_host }}"
  become: yes

- name: Set TRIBES_HOST
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^TRIBES_HOST"
    line: "TRIBES_HOST={{ tribes_host }}"
  become: yes
  when: not hostvars[inventory_hostname].testnet

- name: Set TRIBES_HOST
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^TRIBES_HOST"
    line: "TRIBES_HOST={{ tribes_host_staging }}"
  become: yes
  when: hostvars[inventory_hostname].testnet

- name: Set PHOTON_APP_ID
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^PHOTON_APP_ID"
    line: "PHOTON_APP_ID={{ hostvars[inventory_hostname].photon_app_id }}"
  become: yes

- name: Set MEDIA_HOST
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^MEDIA_HOST"
    line: "MEDIA_HOST={{ media_host }}"
  become: yes
  when: not hostvars[inventory_hostname].testnet

- name: Set MEDIA_HOST
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^MEDIA_HOST"
    line: "MEDIA_HOST={{ media_host_staging }}"
  become: yes
  when: hostvars[inventory_hostname].testnet

- name: Set MACAROON_LOCATION
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^MACAROON_LOCATION"
    line: "MACAROON_LOCATION=/relay/.lnd/data/chain/bitcoin/testnet/admin.macaroon"
  become: yes
  when: hostvars[inventory_hostname].testnet

- name: Set MACAROON_LOCATION
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^MACAROON_LOCATION"
    line: "MACAROON_LOCATION=/relay/.lnd/data/chain/bitcoin/mainnet/admin.macaroon"
  become: yes
  when: not hostvars[inventory_hostname].testnet

- name: Set SOCKET_ENDPOINT
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^SOCKET_ENDPOINT"
    line: "SOCKET_ENDPOINT=ws://{{ inventory_hostname }}"
  become: yes

- name: Mkdir client path dir
  file:
    path: "{{ game_path }}"
    state: directory
    owner: ubuntu
  become: true
  tags: provisioning

- name: add github private ssh key
  copy: >
    src=~/.ssh/id_rsa.github
    dest=/root/.ssh/id_rsa.github
    owner=root
    group=root
    mode=0600
  become: yes

- name: add github public ssh key
  copy: >
    src=~/.ssh/id_rsa.github.pub
    dest=/root/.ssh/id_rsa.github.pub
    owner=root
    group=root
    mode=0600
  become: yes

- name: configure ssh to use ansible key for github.com
  template: >
    src=templates/ssh_config.j2
    dest=/root/.ssh/config
    owner=root
    group=root
    mode=0644
  become: yes

- name: Add and load private key to ssh-agent
  shell: "eval `ssh-agent -s` && ssh-add /root/.ssh/id_rsa.github"
  become: yes

- name: Set authorized key took from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.github.pub') }}"
  become: yes

- name: clone a private repository
  git: >
    repo={{ git_repo }}
    key_file=/root/.ssh/id_rsa.github
    dest={{ game_path }}
    version={{ git_branch }}
    force=yes
    update=yes
  become: yes

- name: Modify .profile
  lineinfile:
    dest: ~/.profile
    create: yes
    state: present
    line: "cd /game"

- name: Modify .profile
  lineinfile:
    dest: ~/.profile
    create: yes
    state: present
    line: "sudo -s"

- name: Setup .lnd
  shell: "cd /game && mkdir .lnd && cp docker/lnd.sample.conf .lnd/lnd.conf"
  become: yes
  when: not hostvars[inventory_hostname].testnet

- name: Modify thunderhub accounts.
  template: >
    src=templates/thubConfig.yaml.j2
    dest=/game/.lnd/thubConfig.yaml
    owner=root
    group=root
    mode=0644
  become: yes

- name: Create thunderhub .cookie
  shell: "touch /game/.lnd/.cookie"
  become: yes

- name: Start container
  shell: "cd /game && docker-compose up -d"
  become: yes
  when: not hostvars[inventory_hostname].testnet

- name: Start container [testnet]
  shell: "cd /game && docker-compose -f docker-compose-testnet.yml up -d"
  become: yes
  when: hostvars[inventory_hostname].testnet

- name: Timeout
  pause:
    seconds: 10
